version: "3"
services:
  postgres:
    image: postgres:latest
    volumes:
      - postgres-db:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: "grocery_booking"
      POSTGRES_USER: "yug"
      POSTGRES_PASSWORD: "password"
    ports:
      - "5432:5432"

  app:
    build: .
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
    depends_on:
      - postgres

volumes:
  postgres-db:
